// @flow
/*::
import type {Publication, PublicationDocument} from './types.js.flow'
*/
/**
 * Filters the publication's attachments to find the publication's Table of Contents
 */
const { arrify } = require('../utils/arrify.js')
const debug = require('debug')('vonnegut:state:getToC')
function getToC (publication /*: Publication */) /*: PublicationDocument */ {
  const contents = arrify(publication.tag)
    .filter(tag => tag.rel === 'contents')
    .map(tag => tag.href)
  const toc = arrify(publication.attachment).filter(
    doc => contents.indexOf(doc.id) !== -1
  )[0]
  return (
    toc || {
      type: 'Document',
      id: publication.id + '?autogeneratedToC',
      name: 'Table of Contents',
      contents: generateToC(publication) // We should autogenerate a ToC from the publication's orderedItems
    }
  )
}
// View then needs to process links to make sure they point at the right place.
function generateToC (publication) {
  const list = arrify(publication.orderedItems).map(chapter => {
    return { id: chapter.id, name: chapter.name, children: [] }
  })
  debug('got toc')
  return list
}
module.exports.getToC = getToC
