// @flow
/*::
import type {Publication, PublicationDocument} from './types.js.flow'
*/
/**
 * Filters the publication's attachments to find the publication's Table of Contents
 */
const { arrify } = require('../utils/arrify.js')
function getToC (publication /*: Publication */) /*: PublicationDocument */ {
  const contents = arrify(publication.tag)
    .filter(tag => tag.rel === 'contents')
    .map(tag => tag.href)
  const toc = arrify(publication.attachment).filter(
    doc => contents.indexOf(doc.id) !== -1
  )[0]
  return (
    toc || {
      type: 'Document',
      id: publication.id + '?autogeneratedToC',
      name: 'Table of Contents',
      contents: 'ToC Missing!' // We should autogenerate a ToC from the publication's orderedItems
    }
  )
}

module.exports.getToC = getToC
