const { arrify } = require('../utils/arrify.js')
const { getDocuments, getDocumentsById } = require('./getDocuments.js')
const debug = require('debug')('vonnegut:state:toBookCard')
/**
 * Converts an ActivityStreams publication type into an easier to handle BookCard state object.
 */
function toBookCard (publication) {
  debug(publication.id)
  // The only thing missing at the moment are sessions and an autogenerated ToC
  const state = {
    id: publication.id,
    name: publication.name || '',
    documents: getDocuments(publication),
    documentsById: getDocumentsById(publication)
  }
  state.orderedItems = arrify(publication.orderedItems).map((item, index) => {
    return state.documentsById[item.id]
  })
  return state
}

module.exports.toBookCard = toBookCard
